### ISSUE TITLE
Cannot modify the panic hook from a panicking thread

### ISSUE THREAD

**Issue by 0xtsukino** [tlsnotary/tlsn-extension#27]
It seems that if the wasm libs failed once, any subsequent requests would also panicked until the browser extension is reloaded.

I suspect we need to manually close some threads after an error from wasm, but I cannot catch uncaught error inside wasm.

<img width="809" alt="Screen Shot 2023-11-15 at 8 29 39 AM" src="https://github.com/tlsnotary/tlsn-extension/assets/87639218/952ed57d-b5cd-48b2-bafe-d5fb66bcd160">

**Comment by mhchia** [comment]
When the wasm module panic we need to instantiate a new one to restart. It seems we can catch errors but we cannot catch panics. IMO it should make sense to replace all `unwrap` in our lib.rs to return errors, like using `?`. And we can catch them in javascript and reuse the same wasm module
