### ISSUE TITLE
Remove `connection: close` headers override

### ISSUE THREAD

**Issue by 0xtsukino** [tlsnotary/tlsn-extension#28]
Currently we have to override `Connection` and `Accept-Encoding` in order to for a request to work. Need to investigate why these overrides are needed, and find solutions to remove headers override from notarization flow. The request theoretically should work with just headers from user browser history.

Edit 1: overriding request header with `accept-encoding: identity` is expected behavior

**Comment by themighty1** [comment]
@0xtsukino, the prover  uses `accept-encoding: identity` to tell the server not to use http compression (like gzip) for the response. 
If the server sent a compressed response, the parties would have to decompress it in MPC which would be prohibitively expensive.

**Comment by 0xtsukino** [comment]
Thanks @themighty1 - that makes sense, so `accept-encoding: identity` is expected behavior.
