### ISSUE TITLE
Mac OS M3 failed to run custom build command for `ring v0.17.6`

### ISSUE THREAD

**Issue by wxd56987** [tlsnotary/tlsn-extension#29]
mac verison: 14.1 (23B2073)
rust verison: rustc 1.76.0-nightly (5facb422f 2023-11-28)
node version: v18.0.0

run build:wasm: failed to run custom build command for `ring v0.17.6`

<img width="1218" alt="image" src="https://github.com/tlsnotary/tlsn-extension/assets/24423810/19b3b245-6a27-449f-89c6-35592ea77b65">

**Comment by 0xtsukino** [comment]
im getting same issue on my machine - still looking for a fix

**Comment by mhchia** [comment]
Encountered this one and solved it with this approach: https://github.com/rust-bitcoin/rust-secp256k1/pull/254#issuecomment-879588601. So we'd need to install llvm from brew
```
brew install llvm
```
and force to use this version of `clang` when building the wasm

```bash
AR=/usr/local/opt/llvm/bin/llvm-ar CC=/usr/local/opt/llvm/bin/clang npm run build:wasm
```
